backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('school/', include('school.urls')),

    # path('api-auth/', include('rest_framework.urls')) django rest framework
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from school import views

urlpatterns = [
    path('index', views.index_view, name='index'),
    path('signup', views.sign_up_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('password-change', auth_views.PasswordChangeView.as_view(
        template_name='registration/password-change.html'), name='password-change'),
    path('password-change/done', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password-change-complete.html'), name='password-change-complete'),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='registration/password-reset.html'), name='password-reset'),
    path('password_reset_done', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password-reset-done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password-reset-confirm.html'), name='password-reset-confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password-reset-complete.html'), name='password-reset-complete'),

    path('parent-dashboard', views.parent_dashboard_view, name='parent-dashboard'),
    path('student-dashboard', views.student_dashboard_view, name='student-dashboard'),
    path('admin-dashboard', views.admin_dashboard_view, name='admin-dashboard'),
    path('students', views.student_list_view, name='student-list'),
    path('add-student', views.add_student_view, name='add-student'),
    path('edit-student/<int:id>', views.edit_student_view, name='edit-student'),
    path('student-details/<int:id>', views.get_students_details_view, name='student-details'),
    path('delete-student/<int:id>', views.delete_student_view, name='delete-student'),
    path('add-teacher', views.create_teacher_view, name='add-teacher'),
    path('teachers', views.teachers_list_view, name='teachers-list'),
    path('teacher-dashboard/<int:id>', views.teacher_dashboard_view, name='teacher-dashboard'),
    path('edit-teacher/<int:id>', views.edit_teacher_view, name='edit-teacher'),
    path('create-department', views.create_department_view, name='create-department'),
    path('departments', views.departments_list_view, name='departments'),
    path('department-detail/<str:code>', views.department_details_view, name='department-details'),
    path('edit-department/<int:id>', views.edit_department_view, name='edit-department'),
    path('subjects', views.subjects_list_view, name='subjects'),
    path('add-subject', views.create_subject_view, name='add-subject'),
    path('edit-subject/<int:id>', views.edit_subject_view, name='edit-subject'),
    path('delete-subject/<int:id>', views.delete_subject_view, name='delete-subject'),
    path('exams', views.exams_list_view, name='exams'),
    path('add-exam', views.create_exam_view, name='add-exam'),
    path('edit-exam/<int:id>', views.edit_exam_view, name='edit-exam'),
    path('delete-exam/<int:id>', views.delete_exam_view, name='delete-exam'),
    path('attendance-success', views.attendance_success, name='attendance-success'),
    path('mark-attendance', views.mark_attendance_view, name='mark-attendance'),
    path('download', views.download_students_excel_view, name='download'),
    path('create-announcement', views.create_announcemennt_view, name='create-announcement'),
    path('announcements', views.announcements_list_view, name='announcements'),
    path('announcements/<int:id>', views.edit_announcemnt_view, name='edit-announcement'),
    path('delete-announcement/<int:id>', views.delete_announcement_view, name='delete-announcement'),
    path('download-notices', views.download_notices_excel_view, name='download-notices'),
    path('add-results/<int:id>', views.add_students_results_view, name='add-results'),
    path('settings', views.settings_page_view, name='settings'),

]

school/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.core.exceptions import ValidationError

# Create your models here.
class CustomUser(AbstractUser):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_authorized = models.BooleanField(default=False)
    role = models.CharField(max_length=20, choices=(
        ('Teacher', 'Teacher'),
        ('Student', 'Student'),
        ('Admin', 'Admin'),
        ('Parent', 'Parent')

    ))
    user_photo = models.ImageField(upload_to='users/', default='../static/images/defaultavatar.jpg')

    is_student = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_parent = models.BooleanField(default=False)

    groups = models.ManyToManyField(
        'auth.Group',
        related_name = 'customuser_set',
        blank = True
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_permissions_set',
        blank = True
    )

    def __str__(self):
        return self.email
    
    
class Teacher(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10, choices=(
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others')
    ))
    title = models.CharField(max_length=10, choices=(
        ('Miss', 'Miss'),
        ('Mr', 'Mr'),
        ('Mrs', 'Mrs')
    ))
    teacher_image = models.ImageField(upload_to='teacher/', blank=True, default='')
    teachers_department = models.ForeignKey('Department', null=True, blank=True, on_delete=models.SET_NULL, related_name='teachers')

    def __str__(self):
        return self.user.username
    
class SchoolClass(models.Model):
    name = models.CharField(max_length=100)
    stream = models.CharField(max_length=10, choices=(
        ('Blue', 'Blue'),
        ('Red', 'Red'),
        ('Yellow', 'Yellow'),
        ('Green', 'Green'),

    ))
    class_teacher = models.OneToOneField(Teacher, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'School Classes'

    def __str__(self):
        return f"{self.name} {self.stream}"

class Subject(models.Model):
    name = models.CharField(max_length=100)
    class_assigned = models.ForeignKey(SchoolClass, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, null=True, on_delete=models.SET_NULL, blank=True, related_name='subjects')
    subjects_department = models.ForeignKey('Department', null=True, blank=True, on_delete=models.SET_NULL, related_name='subjects')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

class Exam(models.Model):
    name = models.CharField(max_length=100, choices=(
        ('CAT 1', 'CAT 1'),
        ('CAT 2', 'CAT 2'),
        ('End Term', 'End Term')
    ))
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    exam_date = models.DateTimeField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

class ExamTimetable(models.Model):
    title = models.CharField(max_length=200)
    class_assigned = models.ManyToManyField(SchoolClass)
    timetable_pdf = models.FileField(upload_to='timetables/')
    is_active = models.BooleanField(default=True)

class Student(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    student_id = models.CharField(max_length=100)
    gender = models.CharField(max_length=10, choices=[
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others')
    ])
    date_of_birth = models.DateField()
    student_class = models.ForeignKey(SchoolClass, on_delete=models.CASCADE)
    religion = models.CharField(max_length=20)
    joining_date = models.DateField()
    admission_number = models.CharField(max_length=15, unique=True)
    student_image = models.ImageField(upload_to='student/', blank=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.user.first_name}-{self.user.last_name}-{self.student_id}")
        super(Student, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.first_name}  {self.user.last_name} ({self.admission_number})"
    
class Parent(models.Model):
    name = models.CharField(max_length=100, blank=True)
    relationship_with_student = models.CharField(max_length=20, choices=(
        ('Father', 'Father'),
        ('Mother', 'Mother'),
        ('Guardian', 'Guardian'),
    ))
    mobile = models.CharField(max_length=10)
    present_address = models.TextField()
    permanent_address = models.TextField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Attendance(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=((
        'Present', 'Present'),
        ('Absent', 'Absent'), 
        ('Late', 'Late')
    ))

class Result(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    score = models.FloatField()

class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=10, unique=True)
    description = models.TextField()
    head = models.ForeignKey(Teacher, null=True, blank=True, on_delete=models.SET_NULL)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def clean(self):
        if self.head and self.head.teachers_department != self:
            raise ValidationError("The department head must be a member in this department")
    
    def __str__(self):
        return f"{self.name} Department"
    

class Notice(models.Model):
    title = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    posted_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    target_audience = models.CharField(
        max_length=100,
        choices = [
            ('Everyone', 'Everyone'),
            ('Students', 'Students'),
            ('Staff', 'Staff')
        ],
        default='Everyone'
    )
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    

school/templates/school/attendance-success.html
<html>
    <head>
        <title>Succcess</title>
    </head>
    <body>
        <h2>Attendace marked successfully</h2>
    </body>
</html>

school/templates/school/index.html
{% extends "form.html" %}
{% load static %}

{% block title %}EduSphere | Home{% endblock %}
{% block content%}
    <div class="home-page">
        <div class="w-full navbar flex justify-between border-0 border-b-gray-100 shadow shadow-gray-100 
            items-center p-6">
            <div class="logo">
                <h2 class="font-bold text-blue-400">EduSphere🌐</h2>
            </div>
            <div class="links flex gap-7">
                <a href="{% url 'signup' %}" class="text-gray-600 font-semibold hover:text-blue-400 transition-colors duration-100">Sign Up</a>
                <a href="{% url 'login' %}" class="text-gray-600 font-semibold hover:text-blue-400 transition-colors duration-100">Login</a>
                <a href="{% url 'signup' %}" class="text-gray-600 font-semibold hover:text-blue-400 transition-colors duration-100">Contact Us</a>
            </div>
        </div>
        <div class="hero-section w-full flex mt-6">
            <div class="left-section w-1/2 flex flex-col gap-2 justify-center px-6 py-8 itemsenter pl-16">
                <h1 class="text-6xl leading-18 font-bold text-gray-600">Simplify School Management</h1>
                <p class="text-gray-400 text-sm sm:text-base my-4">
                    Streamline your administrative tasks with our <br>intuitive platform
                </p>
                <a href="{% url 'signup' %}" class="py-3 font-bold text-center border border-b-blue w-32 h-12 text-sm tracking-wide
                 text-white bg-gray-500 rounded ">Get Started</a>
                
            </div>
            <div class="righ-section w-1/2">
                <img src="{% static 'images/transparentHeroBg.png' %}" alt="students">
            </div>
        </div>
    </div>
{% endblock %}

school/templates/school/student-details.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block content %}
    <div class="main-content col-span-6 ">
        <div class="grid grid-cols-12 lg:grid-cols-7 h-full  gap-2 lg:gap-6">
            <div class="top-banner p-3 col-span-full mx-3
                lg:mx-0 md:col-span-8 sm:col-span-8 lg:col-span-5">
                <div class="p-3 bg-blue-400 text-white h-32 flex justify-between items-center mb-3">
                    <div class="left-section">
                        <h1 class="font-semibold text-2xl uppercase">{{student.user.first_name}} {{ student.user.last_name}}</h1>
                        <div class="flex gap-2 mt-2">
                            <p class="font-medium text-sm">ADMISSION NO. {{student.admission_number}}</p>
                            <p class="font-medium text-sm">CLASS: {{student.student_class.name}} {{student.student_class.get_stream_display}}</p>
                        </div>
                    </div>
                    <div class="right-section flex items-center gap-2">
                        {% if request.user.is_admin %}
                        {% comment %}  {% endcomment %}
                            <a href="{% url 'edit-student' student.user.id %}" class="bg-white text-blue-400 rounded
                                p-2 text-center w-26 text-sm h-10 hover:transition hover:duration-150
                                ">
                                Edit
                            </a>

                            <a href="{% url 'add-results' student.user.id %}" class=" bg-white text-blue-400 rounded
                                p-2 text-center w-28 text-sm h-10 hover:transition hover:duration-150">
                                Add Results
                            </a>
                        {% endif %}
                        <img src="{{student.student_image.url}}" alt="{{student.user.first_name}}" class="rounded-full w-16 h-16">
                    </div>
                </div>

                <div class="shadow shadow-gray-100 border border-gray-100 text-gray-500 p-3 mb-3">
                    <h2 class="text-gray-400 w-fit text-xl font-medium my-4
                        border-0 border-b border-b-gray-300">Personal Info</h2>
                    <div class="info-details flex flex-col gap-2 ">
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Date of Birth:</p>
                            <p class="w-1/2">{{ student.date_of_birth }}</p>
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Gender:</p>
                            <p class="w-1/2">{{ student.get_gender_display }}</p>
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Email:</p>
                            <p class="w-1/2">{{ student.user.email }}</p>
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Mother:</p>
                            <p class="w-1/2">{{ students_mum.name }}</p>
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Mother's Phone:</p>
                            <p class="w-1/2">{{ students_mum.mobile }}</p>
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Father:</p>
                            <p class="w-1/2">{{ students_dad.name }}</p>

                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Father's Phone:</p>
                            <p class="w-1/2">{{ students_dad.mobile }}</p>  
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Present Address:</p>
                            <p class="w-1/2">{{ students_mum.present_address }}</p>
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Permanent Address:</p>
                            <p class="w-1/2">{{ students_mum.permanent_address }}</p>
                        </div>
                    </div>
                </div>

                <div class="shadow shadow-gray-100 text-gray-500 p-3 mb-3">
                    <h2 class="text-gray-400 w-fit text-xl font-medium my-4
                        border-0 border-b border-b-gray-300"> Academics</h2>
                    <div class="info-details flex flex-col">
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Current Class:</p>
                            <p class="w-1/2">{{student.student_class.name}} {{student.student_class.get_stream_display}}</p>
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Class Teacher:</p>
                            <p class="w-1/2">
                                {{student.student_class.class_teacher.get_title_display}}. {{student.student_class.class_teacher.user.first_name}} {{student.student_class.class_teacher.user.last_name}}</p>
                        </div>
                        <div class="text-base flex">
                            <p class="w-1/2 font-medium">Subjects:</p>
                            <ul class=" lisdisc">
                                {% for sc in students_subjects %}
                                    <li>{{ sc.name}}</li>
                                {% endfor %}
                            </ul>
                           
                        </div>
                        

                        
                    </div>
                </div>
                <div class="shadow shadow-gray-100 text-gray-500 p-3 mb-3">
                    <h2 class="text-gray-400 w-fit text-xl font-medium my-4
                        border-0 border-b border-b-gray-300"> Exam Performance</h2>
                    <div class="info-details flex flex-col gap-5">

                        <div class="btns flex gap-8 my-2">
                            <button id="cat1-btn" class="w-30 h-9 p-2 text-gray-400 text-sm border border-gray-200 rounded  shadow shadow-gray-200">CAT 1</button>
                            <button id="cat2-btn" class="w-30 h-9  p-2 text-gray-400 text-sm border border-gray-200 rounded shadow shadow-gray-200">CAT 2</button>
                            <button id="endterm-btn" class="w-30 h-9 p-2 text-gray-400 text-sm border border-gray-200 rounded  shadow shadow-gray-200">END TERM</button>
                        </div>

                       
                        <div class="cat-1" id="cat1-results">
                            <p class="font-medium text-lg text-blue-400">CAT 1 </p>
                            {% for rs in cat1_results %}
                                <div class="flex text-base">
                                    <p class="w-1/2 font-medium">{{rs.exam.subject.name}} </p>
                                    <p class="w-1/2">{{rs.score}}</p>
                                </div>
                            
                            {% endfor %}
                        </div>  
                        
                        <div class="cat-2 hidden" id="cat2-results">
                            <p class="font-medium text-lg text-blue-400">CAT 2 </p>
                            {% for rs in cat2_results %}
                                <div class="flex text-base">
                                    <p class="w-1/2 font-medium">{{rs.exam.subject.name}} </p>
                                    <p class="w-1/2">{{rs.score}}</p>
                                </div>
                            
                            {% endfor %}
                        </div>  

                        <div class="end-term hidden" id="endterm-results">
                            <p class="font-medium text-lg text-blue-400">END TERM </p>
                            {% for rs in endterm_results %}
                                <div class="flex text-base">
                                    <p class="w-1/2 font-medium">{{rs.exam.subject.name}} </p>
                                    <p class="w-1/2">{{rs.score}}</p>
                                </div>
                            
                            {% endfor %}
                        </div>  
                    </div>
                </div>
               
            </div>
            <div class="p-4 col-span-full sm:col-span-4 lg:col-span-2 h-full low-300 ">
                <div class="student-stats flex justify-between gap-2 border-gray-100 
                    px-4 py-8 h-14 shadow shadow-gray-200">
                    <div class="absentism flex flex-col gap-0.5 justify-center">
                        <h5 class="font-semibold">Attendance</h5>
                        <p class="text-green-600 text-xl font-bold text-center">{{ present_days }}</p>
                    </div>
                    <div class="attendace flex flex-col gap-0.5 justify-center">
                        <h5 class="font-semibold">Absent</h5>
                        <p class="text-xl font-bold text-center text-red-500">{{ absent_days }}</p>
                    </div>

                    <div class="attendace flex flex-col gap-0.5 justify-center">
                        <h5 class="font-semibold">Late</h5>
                        <p class="text-xl font-bold text-center text-orange-400">{{ late_days }}</p>
                    </div>
                    
                </div>
                <div class="student-stats flex flex-col gap-2 border-gray-100  mt-7
                    px-4 py-8 4 shadow shadow-gray-200">
                    <div class="cat1 flex gap-0.5  justify-between">
                        <h5 class="font-semibold">CAT 1</h5>
                        <p class="text-green-600 ">{{ total_score_cat1 }}</p>
                    </div>
                    <div class="cat2 flex gap-0.5 justify-between">
                        <h5 class="font-semibold">CAT 2</h5>
                        <p class=" text-red-500">{{ total_score_cat2 }}</p>
                    </div>

                    <div class="endterm flex gap-0.5 justify-between">
                        <h5 class="font-semibold">END TERM</h5>
                        <p class="  text-orange-400">{{ total_score_endterm }}</p>
                    </div>
                    
                </div>

                <div class="announcements mt-7 ">
                    <h3 class="font-semibold text-blue-400 text-lg"> Announcements</h3>
                    <ul>
                        {% if latest_announcements %}
                            {% for announcement in latest_announcements %}
                                <li class="listt text-gray-500 list-none text-sm min-h-10 py-1 border-0 border-b border-b-gray-200">{{announcement.title}}
                                    <span class="text-gray-400 text-sm">{{ announcement.created_at|naturaltime }}</span></li>
                            
                            {% endfor %}
                            {% else %}
                            <p>No recent activities</p>
                        {% endif %}
                    </ul>
                    
                </div>
                
            </div>

        </div>
    </div>
</div>

{% endblock content %}

school/templates/school/subjects.html
{% extends 'base.html' %}
{% block content %}
<div class="subjects-section p-6">
    <div class="flex justify-between items-center h-20 py-1">
        <h3 class="text-gray-400 text-xl font-bold my-4">Subjects</h3>
        <div class="hidden lg:flex gap-2">
            
            <button class="h-7 w-7 rounded-full text-base bg-blue-400 text-white
                border border-blue-400 text-center font-normal">
                <i class="fa fa-arrow-down edit-icon"></i>
            </button>
            <a href="{% url 'add-subject' %}" class="h-7 w-7 rounded-full text-base text-blue-400 bg-white
            border border-blue-400 text-center font-normal  edit-blue-icon">
            <i class="fa fa-plus edit-blue-icon"></i>
            </a>
        </div>

        <div class="flex lg:hidden gap-1 relative">
            <button class="h-7 w-7 rounded-full text-base text-white
                border-0 text-center font-normal cursor-pointer" id="ellipsis-btn">
                <i class="fa-solid fa-ellipsis-vertical gray-icon"></i>
            </button>
            
            

            <ul id="ellipsis-menu" class="absolute z-50 right-6 hidden rounded shadow
                px-1 py-3 -mt-6 w-26 shadow-gray-300 fle-col gap-1 transition-all duration-200">
                <li class="text-sm text-gray-400 border-0 border-b border-b-gray-200 pb-0.5 mb-1">
                    <a href="">Add Student</a>
                </li>
                <li class="text-sm text-gray-400 border-0 border-b border-b-gray-200 pb-0.5 mb-1">
                    <button href="">Download</button>
                </li>
                <li class="text-sm text-gray-400 border-0 border-b border-b-gray-200 pb-0.5 mb-1">
                    <button class="w-7 rounded-full text-gray-400 text-sm
                        border-0 text-center font-normal cursor-pointer" id="search-btn">
                        Search
                    </button>
                </li>
            </ul>
        </div>
    </div>
    <div class="search-input w-full hidden lg:hidden mb-3" id="search-input">
        <input 
            type="text" 
            name="search" 
            id="search" 
            placeholder="Search here"
            class="placeholder-gray-300 w-full rounded-md bg-white text-gray-700 border 
            border-gray-200 h-10 p-2 focus:border-gray-400 focus:outline-0"
        >
    </div>
    <table class="w-full text-left border border-gray-200 rounded-xl mt-8">
        <thead class="bg-gray-50 ">
            <tr>
                <th class="py-2 px-3 text-sm md:text-base border-b border-b-gray-200">NO.</th>
                <th class="py-2 px-3 text-sm md:text-base border-b border-b-gray-200">Name</th>
                <th class="py-2 px-3 text-sm md:text-base border-b border-b-gray-200">Class</th>
                <th class="py-2 px-3 text-sm md:text-base border-b border-b-gray-200 hidden md:table-cell">Teacher</th>
                <th class="py-2 px-3 text-sm md:text-base border-b border-b-gray-200 hidden md:table-cell">Department</th>
                <th class="py-2 px-3 text-sm md:text-base border-b border-b-gray-200 hidden md:table-cell">Actions</th>
                
            </tr>
        </thead>
        <tbody class="divide-y divide-gray-300">
            {% for subject  in page_obj %}
                <tr class="hover:bg-gray-50">
                    <td class="py-2 px-3 text-sm md:text-base">{{ forloop.counter }}</td>
                    <td class="py-2 px-3 text-sm md:text-base">{{ subject.name }} </td>
                    <td class="py-2 px-3 text-sm md:text-base">{{ subject.class_assigned.name }} {{ subject.class_assigned.get_stream_display }}</td>
                    <td class="py-2 px-3 text-sm md:text-base hidden md:table-cell">{{ subject.teacher.get_title_display}}. {{ subject.teacher.user.last_name }}</td>
                    <td class="py-2 px-3 text-sm md:text-base hidden md:table-cell"> {{subject.subjects_department.name }}</td>
                    <td class="py-2 px-3 text-sm md:text-base hidden md:flex gap-4">
                        {% if request.user.is_admin %}
                            <a href="{% url 'edit-subject' subject.id %}" class="text-sm text-blue-400 hover:transform hover:scale-105 hover:transition hover:duration-150">
                                <i class="fas fa-pencil-alt edit-blue-icon"></i>
                            </a>
                            <a href="{% url 'delete-subject' subject.id %}" class="text-sm hover:transform hover:scale-105 hover:transition hover:duration-150">
                                <i class="fas fa-trash delete-icon"></i>
                            </a>
                        {% endif %}
                    </td>
                </tr>
                
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination w-full my-6 flex justify-center border-gray-50 shadow shadow-gray-200 
        h-20 py-4">
        <span class="step-links flex gap-8 items-center">
            {% if page_obj.has_previous %}
                <div class="first flex gap-2 items-center">
                    <a class="text-sm text-gray-500 hover:text-blue-400" href="?page=1">FIRST</a>
                    <a class="text-sm text-gray-500 hover:text-blue-400" href="?page={{page_obj.previous_page_number}}">PREV</a>
                </div>
                
            {% endif %}
            <span class="current w-8 h-8 rounded-full text-white bg-gray-500 k  text-center flex 
                text-sm  justify-center items-center">
                {{ page_obj.number }}
            </span>
            {% if page_obj.has_next %}
                <div class="first flex gap-2 items-center">
                    <a class="text-sm text-gray-500 hover:text-blue-400" href="?page={{page_obj.next_page_number}}">NEXT</a>
                    <a class="text-sm text-gray-500 hover:text-blue-400" href="?page={{page_obj.paginator.num_pages}}">LAST</a>
                </div>
            {% endif %}
        </span>
    </div>

</div>
    
{% endblock %}